# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7186f7e6c9d1c1bea7745d152830230e7c5071b27f923eec36a09ee27a1165043bbefe92f45c539279401f7c9f4fc0dd11785eab855a873791e5259d68731789

test:
  secret_key_base: a7e4c77d7770d32384c16209111871c7b38fdf20c5377748cc0b3849002a7d911f2b1590e9a6c679168e3b6c53ee80c34842a004bae99f4f9e1b34c865e04d71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
